### ISSUE TITLE
Please add support for iOS simulator

### ISSUE THREAD

**Issue by houmie** [jzau/tun2sockskit#1]
Hello,

Thank you for adding this project to Github. It's a great service to the iOS community.

After your latest fix, it all works fine on device. However when I try to run it on the simulator to take screenshots for AppStore, I get this error:

> Showing All Messages
> /Users/houmie/Library/Developer/Xcode/DerivedData/xxxx-dttitroctcsubrepierfgmszsibu/SourcePackages/artifacts/tun2sockskit/HevSocks5Tunnel/HevSocks5Tunnel.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/houmie/Library/Developer/Xcode/DerivedData/xxxx-dttitroctcsubrepierfgmszsibu/SourcePackages/artifacts/tun2sockskit/HevSocks5Tunnel/HevSocks5Tunnel.xcframework'.

It is really important for the simulator to work as well. Do you think you could add support for it?

Thanks,

**Comment by houmie** [comment]
@jzau I hope you have seen this, issue. Thanks

**Comment by jzau** [comment]
Hey @houmie This repo was done by someone else, and somehow it got removed so I pushed my local copy here. Maybe have a look at this copy for simulator support https://github.com/dumpmemory/Tun2SocksKit. Feel free to raise a PR 😄

**Comment by jzau** [comment]
I've found some copies and added them back.

**Comment by houmie** [comment]
Ah Thank you. 👍🏼   Yeah I don't know what happened to Arror's repo.  But he definitely had the support for simulators. 
Thanks for adding it. I will check it out in a moment and let you know if it works.
